### ISSUE TITLE
Returns Status 400

### ISSUE THREAD

**Issue by jjrchrds** [marieqg/contact-form-medium#1]
This is great! Thank you for the tutorial! I’m getting stuck when testing sendEmail with Postman, and I’m really not sure what I’m doing wrong.

I set up process.env environment in Postman, with the three env vars.
I copied the function url into Postman, then used Post with an object with the three keys.
I keep getting:
{“statusCode”:400}

when I look in netlify function sendEmail I see:
12:23:28 AM: 2020–07–29T04:23:28.588Z undefined ERROR (node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
12:23:28 AM: Duration: 131.60 ms Memory Usage: 78 MB Init Duration: 247.02 ms
Any thoughts?

**Comment by marieqg** [comment]
Hello, 
Thanks for your kind words! 
I don't think the error 400 has something to do with your Buffer warning. I have the same warning and my function is working. It's most likely a syntax issue, can you show me how is your object?

**Comment by jjrchrds** [comment]
`{
    "name": "Joshua",
    "email": "joshua.richards@johnst.com",
    "message": "Hello!!!"
}`

**Comment by jjrchrds** [comment]
what should be inside process.env? I currently just have MAILGUN_API_KEY, MAILGUN_DOMAIN, HR_EMAIL_ADDRESS (I changed MY_EMAIL_ADDRESS to HR_EMAIL_ADDRESS)

`
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})
const headers = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
}
const successCode = 200
const errorCode = 400

// Connect to our Mailgun API
const mailgun = require("mailgun-js")
const mg = mailgun({
  apiKey: process.env.MAILGUN_API_KEY,
  domain: process.env.MAILGUN_DOMAIN,
})

// Our Netlify function
export function handler(event, context, callback) {
  let data = JSON.parse(event.body)
  let { name, email, message } = data
  let mailOptions = {
    from: `${name} <${email}>`,
    to: process.env.HR_EMAIL_ADDRESS,
    replyTo: email,
    text: `${message}`,
  }

  // Our MailGun code
  mg.messages().send(mailOptions, function(error, body) {
    console.log(body);
    if (error) {
      callback(null, {
        errorCode,
        headers,
        body: JSON.stringify(error),
      })
    } else {
      callback(null, {
        successCode,
        headers,
        body: JSON.stringify(body),
      })
    }
  })
}`

**Comment by marieqg** [comment]
The object looks good.  You only have those three parameters in the
process.env . Do you have a repo with your project?

Le jeu. 30 juil. 2020 à 00:10, Joshua Richards <notifications@github.com> a
écrit :

**Comment by jjrchrds** [comment]
And... it's working. No idea what changed. Thank you for your help regardless!

Now, if you have a tutorial about firebase schedule functions and mailgun, or some other way to schedule mailgun to send an email daily...
